title: Threadspool
description: Tech blog with weekly mini topics
location: Bengaluru, India
avatar: /avatar.png
baseurl: ""
url: "https://www.gourishbiradar.com"
github_username: gourishbiradar
google_analytics: G-EWDWYYS1E1
email: biradar.gourish@gmail.com
linkedin_url: https://www.linkedin.com/in/gourishkbiradar

paginate: 5
paginate_path: /posts/page:num/

plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - _docs/
  - Gemfile
  - Gemfile.lock
  - Makefile
  - CLAUDE.md
  - README.md
  - Gourish_Biradar_Resume.pdf
  - .bundle/
